<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>Get Token</name>
   <tag></tag>
   <elementGuidId>4871471d-4218-49d3-ada6-28077088cd04</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <autoUpdateContent>true</autoUpdateContent>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent></httpBodyContent>
   <httpBodyType></httpBodyType>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>authority</name>
      <type>Main</type>
      <value>gorest.co.in</value>
      <webElementGuid>c1675756-638e-4e12-8c56-018f0a97abef</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept</name>
      <type>Main</type>
      <value>text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7</value>
      <webElementGuid>5c7343fb-efe9-4d71-a6a6-022e02a1dea3</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept-language</name>
      <type>Main</type>
      <value>en-US,en;q=0.9</value>
      <webElementGuid>47990680-3f5c-4bf3-869e-b3bf4a6ca9d9</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cookie</name>
      <type>Main</type>
      <value>_ga=GA1.1.460262528.1682480176; _gorest_session=N8%2FEUB82GAQ4sfgbPJBKeOLzY0hGxE7HwE2oi8fHfBD5rSUWM%2Bog95zxWlvx%2B4d%2B3sCCWEGa%2FuxzwVlJh6tUX0FQECWeuaB5Xu46PhSBBLjI7IXczeAUbRJLErV40MTU3ryK0MgQVtPaosA2txmcIl46hCuI%2By0rIQjVvzUMvCM%2FbE0Pc7ls2pK%2BY4SzLHQ5ckhXD9bWB7Jy8JHZtyed0uugfIJ2xxKYwBD1WAcRsIsSX39oiXfdcqWKfndHrtEFGrZBFC2laKOSa17t8rMO5Y6sBeJHhNpqjTNHqj5yS2uoZzaekG9osyPi6XTwUssd8bNGS1vyDQZt%2BdDIc2yKhuZhs2Vp352pxmnYGPDwbt9G6OkEoxG4s7diiNeNvl2kwDiKUUR8ZWbr8iDlSyIzF2HAJC1jo%2BQND0uiLoFlH7B89eg%3D--TK82T4AqHhdPM87D--l1W0yw6hVJpsHcwSH1nVmg%3D%3D; _ga_7KR6VNWHWS=GS1.1.1683772431.14.1.1683773055.0.0.0</value>
      <webElementGuid>94c63c2a-e5ed-4ee6-b8c6-8853e26c1e3c</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>referer</name>
      <type>Main</type>
      <value>https://gorest.co.in/</value>
      <webElementGuid>083dbecb-9aef-4e01-92f2-a0f83467a18b</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sec-ch-ua</name>
      <type>Main</type>
      <value>&quot;Google Chrome&quot;;v=&quot;113&quot;, &quot;Chromium&quot;;v=&quot;113&quot;, &quot;Not-A.Brand&quot;;v=&quot;24&quot;</value>
      <webElementGuid>30633d9a-9add-4978-87e1-1f7908d57785</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sec-ch-ua-mobile</name>
      <type>Main</type>
      <value>?0</value>
      <webElementGuid>31dc7c9f-d8ec-43e8-ad29-fc33be139841</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sec-ch-ua-platform</name>
      <type>Main</type>
      <value>&quot;Windows&quot;</value>
      <webElementGuid>0d714107-0520-4d51-89b9-4573569d281c</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sec-fetch-dest</name>
      <type>Main</type>
      <value>document</value>
      <webElementGuid>1d7fd00b-7b73-477e-8019-8002655b252c</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sec-fetch-mode</name>
      <type>Main</type>
      <value>navigate</value>
      <webElementGuid>4232602a-dfca-41a7-b3f0-ccabc0b37389</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sec-fetch-site</name>
      <type>Main</type>
      <value>same-origin</value>
      <webElementGuid>2189119c-12d4-4488-8346-88bc11cddc7f</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sec-fetch-user</name>
      <type>Main</type>
      <value>?1</value>
      <webElementGuid>65754c45-b094-4c4b-9d8c-e87ad0b7d1a8</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>upgrade-insecure-requests</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>915ba2e1-f57a-458b-890c-d093fb6e288b</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>user-agent</name>
      <type>Main</type>
      <value>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36</value>
      <webElementGuid>593e30fb-25ec-4139-b16c-4b8f707ad3a8</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Referer</name>
      <type>Main</type>
      <value>https://gorest.co.in/my-account/access-tokens</value>
      <webElementGuid>334c465a-7047-456c-a6e9-fc1e6d8ad482</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>User-Agent</name>
      <type>Main</type>
      <value>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36</value>
      <webElementGuid>f923abb8-9af2-4264-b6f4-af1a88ece851</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Origin</name>
      <type>Main</type>
      <value>https://gorest.co.in</value>
      <webElementGuid>9f075230-3b5e-4e12-9710-359020142b0d</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>content-length</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a9dc2728-b9cc-4d8d-b1bc-e867fbe1c578</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>origin</name>
      <type>Main</type>
      <value>https://gorest.co.in</value>
      <webElementGuid>a831806a-d275-4c66-b736-a62e6036f120</webElementGuid>
   </httpHeaderProperties>
   <katalonVersion>8.6.0</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <restRequestMethod>GET</restRequestMethod>
   <restUrl>https://gorest.co.in/my-account/access-tokens</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
